apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: internship-web
  template:
    metadata:
      labels:
        app: internship-web
    spec:
      containers:
        - name: internship-web
          image: internship-web:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80

