apiVersion: v1
kind: Service
metadata:
  name: web-service
spec:
  type: NodePort
  selector:
    app: internship-web
  ports:
    - port: 80           
      targetPort: 80     # containerPort
      nodePort: 30000    

